config/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from apps.core.views.default import handler403, handler404, handler500, IndexPage, get_index

# from . import api

# URLs that can be seen by Swagger after one has authenticated
# public_apis = [
#     url(r'^api/v1/', include(api)),
# ]

# Remove docs from production
# schema_view = get_schema_view(
#     openapi.Info(
#         title="GAS YETU API DOCS",
#         default_version='v1',
#         description="GAS YETU APIs",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="group.rnd@jambopay.com"),
#     ),
#     permission_classes=(permissions.AllowAny,),
#     public=False,
#     patterns=public_apis,
# )

# docs = [
#     url(r'^docs/$', login_required(schema_view.with_ui('swagger',
#                                                        cache_timeout=None)), name='schema-swagger-ui'),
# ]


# urlpatterns = public_apis + docs + [
urlpatterns = [
    # url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^$', get_index, name='home'),
    url(r'^account/', include('apps.accounts.urls.default', namespace='account')),
    url(r'^account/', include('allauth.urls')),
    url(r'^distribution/', include('apps.distribution.urls.default')),
    url(r'^consumers/', include('apps.consumers.urls.default')),
    url(r'^core/', include('apps.core.urls')),
    url(r'^inventory/', include('apps.inventory.urls.default')),
    url(r'^products/', include('apps.products.urls.default')),
    url(r'^sales/', include('apps.sales.urls.default')),
    url(r'^orders/', include('apps.orders.urls.default')),
    url(r'^admin/', admin.site.urls),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^accounts/login/$', auth_views.LoginView,
        {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', auth_views.LogoutView),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_SITE_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_SITE_TITLE

apps/core/models.py
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    """
    An abstract base class model that provides self updating
    ``created`` and ``modified`` fields.
    """
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    modified_on = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True

    def formatted_date(self, date):
        return '%s' % date.strftime('%m/%d/%Y')


class Country(BaseModel):
    """
    List of Countries
    """
    code = models.CharField(max_length=3, unique=True)
    title = models.CharField(max_length=100, unique=True)
    tel_code = models.CharField(max_length=3, blank=True)

    def __str__(self):
        return '{}'.format(self.title)

    def get_country(self, **kwargs):
        """
        Get Country detail
        Returns:
            Country
        """
        try:
            return Country.objects.get(**kwargs)
        except Country.DoesNotExist:
            return None

    def get_absolute_url(self):
        return reverse(
            'country-update', kwargs={'pk': self.pk}
        )


class Region(BaseModel):
    """
    List of regions in countries. This is equivalent to Counties in Kenya
    """
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    code = models.CharField(max_length=3)
    title = models.CharField(max_length=100)

    class Meta:
        unique_together = (('country', 'code'),)
        ordering = ('title',)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return reverse(
            'region-update', kwargs={'pk': self.pk}
        )


class SubRegion(BaseModel):
    """
    List of sub regions. This is equivalent to Sub Counties in Kenya
    """
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    code = models.CharField(max_length=3)
    title = models.CharField(max_length=100)

    class Meta:
        unique_together = (('region', 'code'),)
        ordering = ('title',)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
            return reverse(
            'sub-region-update', kwargs={'pk': self.pk}
        )


class Location(BaseModel):
    """
    List of locations
    """
    subregion = models.ForeignKey(SubRegion, on_delete=models.CASCADE)
    code = models.CharField(max_length=3)
    title = models.CharField(max_length=100)

    class Meta:
        unique_together = (('subregion', 'code'),)
        ordering = ('title',)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return reverse(
        'location-update', kwargs={'pk': self.pk}
    )



class Village(BaseModel):
    """
    List of Villages
    """
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    code = models.CharField(max_length=3)
    title = models.CharField(max_length=100)

    class Meta:
        unique_together = (('location', 'code'),)
        ordering = ('title',)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return reverse(
            'village-update', kwargs={'pk': self.pk}
        )


class MobileNetworkOperator(BaseModel):
    """
    List of mobile network operators registered in Scholar
    E.g. Safaricom, Airtel, Orange etc
    """
    title = models.CharField(max_length=100)
    short_name = models.CharField(max_length=20)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = (('title', 'country'),)

    def __str__(self):
        return '{} - {}'.format(self.title, self.short_name)


class MobileMoneyOperator(BaseModel):
    """
    List of mobile money operators registered in Scholar
    E.g. Safaricom - Mpesa, Airtel Money, JamboPay etc
    """
    title = models.CharField(max_length=50)
    short_name = models.CharField(max_length=20)
    mobile_network_operator = models.ForeignKey(MobileNetworkOperator, on_delete=models.CASCADE, null=True,
                                                related_name='core_mobilemoneyoperator_networkoperator')
    is_active = models.BooleanField(default=True)
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, related_name='core_mobilemoneyoperator_country')

    class Meta:
        unique_together = (('title', 'country'),)

    def __str__(self):
        return '{} - {}'.format(self.title, self.short_name)

apps/distribution/models.py
import json

from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from apps.core.models import BaseModel, Location, Region, SubRegion
from apps.core.utils import NullableEmailField
from apps.tenants.models import Tenant
from apps.tenants.choices import TENANT_TYPE


class GasImporter(BaseModel):
    """
    GasImporters registered in the system
    """
    gas_importer_tenant = models.OneToOneField(
        Tenant, on_delete=models.CASCADE, related_name='gas_importer')
    trading_name = models.CharField(
        max_length=50, help_text='Business Name')
    contact_email = NullableEmailField(
        _('contact e-mail address'), blank=True, null=True, default=None, unique=True,
        help_text='Contact Email Address')
    contact_phone = models.CharField(
        _('phone number'), max_length=16, null=True,
        blank=True, default=None, help_text='Contact Phone Number'
    )
    identity_number = models.CharField(max_length=20, blank=False)
    agent_number = models.IntegerField(
        unique=True, null=True, blank=True, help_text='Six digit agent number')

    def __str__(self):
        return '{}'.format(self.gas_importer_tenant)


class RetailerManager(models.Manager):
    def create_retailer_merchant(self, business_name, gas_importer, **kwargs):
        retailer_tenant = Tenant.create_new(
            tenant_type=TENANT_TYPE.Retailer, title=business_name)
        retailer = Retailer.objects.create(
            gas_importer=gas_importer,
            retailer_tenant=retailer_tenant,
            trading_name=business_name,
            kra_pin_number=kwargs['kra_pin_number'],
            contact_email=kwargs['email'],
            contact_phone=kwargs['phone'],
            identity_number=kwargs['identity_number'],
            physical_address=kwargs.get('physical_address'),
            sub_region=kwargs['sub_region'],
            agent_number=kwargs['agent_number']
        )
        return retailer


class Retailer(BaseModel):
    """
    Retailers registered in the system

    """
    gas_importer = models.ForeignKey(
        GasImporter, on_delete=models.CASCADE, related_name='gas_importer_retailer')
    retailer_tenant = models.OneToOneField(
        Tenant, on_delete=models.CASCADE, null=True, related_name='retailer')
    sub_region = models.ForeignKey(SubRegion, on_delete=models.CASCADE)
    trading_name = models.CharField(
        max_length=100, help_text='Name of the Retailer')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    agent_number = models.IntegerField(
        unique=True, null=True, blank=True, help_text='Six digit agent number')
    identity_number = models.CharField(max_length=20, blank=False)
    kra_pin_number = models.CharField(max_length=30)
    physical_address = models.CharField(max_length=50, null=True, blank=True)
    contact_phone = models.CharField(max_length=50)
    contact_email = models.CharField(max_length=50, unique=True)
    enabled = models.BooleanField(default=True)

    objects = RetailerManager()

    def __str__(self):
        return '{}'.format(self.retailer_tenant)

    def get_absolute_url(self):
        """
        Returns the URL of the detail page for that retailer.
        """
        return reverse(
            'retailer-update', kwargs={'pk': self.pk}
        )

apps/tenants/models.py
from django.db import models
from django.utils.translation import ugettext as _
from apps.core.models import BaseModel
from apps.core.utils import get_uuid
from simple_history.models import HistoricalRecords

from .choices import TENANT_TYPE


class Tenant(BaseModel):
    """
    Central repository of all tenants in the system
    """
    id = models.UUIDField(primary_key=True, default=get_uuid, editable=False)
    tenant_type = models.PositiveSmallIntegerField(
        choices=TENANT_TYPE, help_text='Type of Tenant')
    title = models.CharField(max_length=100, help_text='Name of the Tenant')
    email = models.EmailField(
        _('email address'), blank=True, null=True, default=None, help_text='Contact Email Address'
    )
    phone = models.CharField(
        _('phone number'), max_length=16, null=True,
        blank=True, default=None, help_text='Contact Phone Number'
    )
    enabled = models.BooleanField(default=True)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.title}'

    @staticmethod
    def create_new(tenant_type, title, commit=True):
        """
        Args:
            tenant_type (int): type of tenant
            title (str): Name of the tenant
            bulk_create (bool): If True, return a created object
        Create a tenant
        """
        if commit:
            return Tenant.objects.create(tenant_type=tenant_type, title=title)
        else:
            return Tenant(tenant_type=tenant_type, title=title)


class TenantBaseModel(BaseModel):
    """
    Base model for all tables that require are have a OneToMany relation with Tenant
    """
    tenant = models.ForeignKey(
        Tenant, on_delete=models.CASCADE)

    class Meta:
        abstract = True

apps/distribution/forms.py
from django import forms
from django.conf import settings
from django.forms import ModelForm, SelectDateWidget
from django.forms.widgets import Select
from django.utils.translation import ugettext_lazy as _

from apps.accounts import messages
from apps.accounts.models import User
from apps.core.models import Region, SubRegion

from .models import Retailer


class RetailerUpdateForm(ModelForm):

    class Meta:
        model = Retailer
        fields = (
            'trading_name',
            'kra_pin_number',
            'identity_number',
            'contact_phone',
            'contact_email',
            'physical_address',
            'sub_region',
            'start_date',
            'end_date'
        )
        widgets = {
            'end_date': forms.DateInput(format=('%d-%m-%Y'),
                                        attrs={'id': 'endDate',
                                               'placeholder': 'Select a date'}),
            'start_date': forms.DateInput(format=('%d-%m-%Y'),
                                          attrs={'id': 'startDate',
                                                 'placeholder': 'Select a date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            self.fields['contact_email'].widget.attrs['readonly'] = True
            self.fields['contact_phone'].widget.attrs['readonly'] = True

apps/distribution/views/api.py
import datetime

from rest_framework import serializers, status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from apps.accounts.choices import EMPLOYEE
from apps.tenants.choices import TENANT_TYPE
from apps.tenants.models import Tenant

from ..models import Distributor, Retailer
from ..serializers import DistributorSerializer, RetailerSerializer


class DistributorViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Distributor.objects.filter(enabled=True)
    serializer_class = DistributorSerializer


class RetailerViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Retailer.objects.filter(enabled=True)
    serializer_class = RetailerSerializer

    def get_queryset(self):
        queryset = super(RetailerViewSet, self).get_queryset()
        user = self.request.user
        if user.profile_type == EMPLOYEE:
            if user.profile.tenant.tenant_type == TENANT_TYPE.Distributor:
                queryset = queryset.filter(
                    distributor=self.request.user.profile.tenant.distributor)
        return queryset

    @action(methods=['patch'], url_path='deactivate', detail=True, url_name='retailer-deactivate')
    def deactivate(self, request, pk=None):
        """
        deactivating a retailer
        """
        try:
            retailer = Retailer.objects.get(id=pk)
        except Retailer.DoesNotExist:
            raise serializers.ValidationError({
                'error': "Retailer does not exist"
            })
        try:
            tenant = Tenant.objects.get(id=retailer.retailer_tenant_id)
        except Tenant.DoesNotExist:
            raise serializers.ValidationError({
                'error': "Tenant does not exist"
            })
        tenant = Tenant.objects.get(id=retailer.retailer_tenant_id)
        tenant.enabled = False
        tenant.save()
        retailer.end_date = datetime.date.today().strftime('%Y-%m-%d')
        retailer.save()
        serializer = RetailerSerializer
        headers = self.get_success_headers(serializer.data)
        data = {'message': f'Retailer {retailer.title} deactivated succesfully'}
        return Response(data, status=status.HTTP_200_OK, headers=headers)

apps/distribution/templates/distribution/distributor/agent_create.html
{% extends "page.html" %}
{% load sass_tags %} {% load widget_tweaks %} {% load static %} {% load i18n %}
{% block title %} Create Distributor{% endblock title %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    {% if form.non_field_errors %}
        <div id="messages">
        {% for message in form.non_field_errors %}
        <div class="alert alert-dismissible alert-danger"
            role="alert">
            <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message|escape }}
        </div>
        {% endfor %}
        </div>
    {% endif %}
    <form class="form-narrow form-2col" id="distributor-form" method="POST" action="" data-parsley-validate data-parsley-excluded=":hidden">
        {% csrf_token %} {{ wizard.management_form }}
        <div class="row">
            <span style="font-size: 35px;">Create New Distributor</span>
            <p><b>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</b></p>
            <hr>
        </div>
        <div class="row">
            <!-- AGENT EMAIL -->
            <div class="form-group{% if form.agent_email.errors %} has-error{% endif %}">
                <label class="control-label" for="id_agent_email">{% trans "Agent Email" %}</label>
                {% render_field form.agent_email class+="form-control input-lg" %}
                <div class="error-block">{{ form.agent_email.errors }}</div>
            </div>
        </div>

        <!-- REDIRECT -->
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" /> {% endif %}

        <div class="text-right m-t-30">
            {% if wizard.steps.prev %}
                <button name="wizard_goto_step" formnovalidate type="submit" value="{{ wizard.steps.prev }}" class="btn btn-default btn-fill btn-wd btn-next btn-reset">{% trans "PREVIOUS" %}</button>
            {% endif %}
            <button type="submit" class="btn btn-success btn-fill btn-wd btn-next">FINISH</button>
        </div>

    </form>

{% endblock page %}

apps/distribution/templates/distribution/distributor/merchant_create.html
{% extends "page.html" %}
{% load sass_tags %} {% load widget_tweaks %} {% load static %} {% load i18n %}
{% block title %} Create Distributor{% endblock title %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    {% if form.non_field_errors %}
        <div id="messages">
        {% for message in form.non_field_errors %}
        <div class="alert alert-dismissible alert-danger"
            role="alert">
            <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message|escape }}
        </div>
        {% endfor %}
        </div>
    {% endif %}
    <form class="form-narrow form-2col" id="distributor-form" method="POST" action="" data-parsley-validate data-parsley-excluded=":hidden">
        {% csrf_token %} {{ wizard.management_form }}
        <div class="row">
            <span style="font-size: 35px;">Create New Distributor</span>
            <p><b>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</b></p>
            <hr>
        </div>
        <div class="row">
            <!-- BUSINESS NAME -->
            <div class="form-group{% if form.business_name.errors %} has-error{% endif %}">
                <label class="control-label" for="id_business_name">{% trans "Business Name" %}</label>
                {% render_field form.business_name class+="form-control input-lg" data-parsley-minlength="5" %}
                <div class="error-block">{{ form.business_name.errors }}</div>
            </div>

            <!-- CONTACT EMAIL -->
            <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                <label class="control-label" for="id_email">{% trans "Contact Email" %}</label>
                {% render_field form.email class+="form-control input-lg" %}
                <div class="error-block">{{ form.email.errors }}</div>
            </div>

            <!-- CONTACT PHONE -->
            <div class="form-group{% if form.phone.errors %} has-error{% endif %}">
                <label class="control-label" for="id_phone">{% trans "Contact Phone" %}</label>
                {% render_field form.phone class+="form-control input-lg" placeholder="07xxxxxxx" data-parsley-required="true" data-parsley-errors-container="#phone-errors" %}
                <p class="help-block small">{% trans "Phone numbers must start with 07 and contain 10 digits" %}</p>
                <div id="phone-errors"></div>
                <div class="error-block">{{form.phone.errors}}</div>
            </div>

            <!-- KRA PIN NUMBER -->
            <div class="form-group{% if form.kra_pin_number.errors %} has-error{% endif %}">
                <label class="control-label" for="id_kra_pin_number">{% trans "Kra Pin Number" %}</label>
                {% render_field form.kra_pin_number class+="form-control input-lg"  data-parsley-minlength="8" data-parsley-required="true" %}
                <div class="error-block">{{ form.kra_pin_number.errors }}</div>
                <div>
                </div>
            </div>

            <!-- IDENTITY NUMBER -->
            <div class="form-group{% if form.identity_number.errors %} has-error{% endif %}">
                <label class="control-label" for="id_identity_number">{% trans "Identity Number" %}</label>
                {% render_field form.identity_number class+="form-control input-lg" data-parsley-minlength="8" %}
                <div class="error-block">{{ form.identity_number.errors }}</div>
            </div>

            <!-- REGION -->
            <div class="form-group{% if form.region.errors %} has-error{% endif %}">
                <label class="control-label" for="id_region">{% trans "County" %}</label>
                {% render_field form.region class+="form-control input-lg" %}
                <div class="error-block">{{ form.region.errors }}</div>
            </div>

            <!-- PHYSICAL ADDRESS -->
             <div class="form-group{% if form.physical_address.errors %} has-error{% endif %}">
                <label class="control-label" for="id_physical_address">{% trans "Physical Address" %}</label>
                {% render_field form.physical_address class+="form-control input-lg" %}
                <div class="error-block">{{ form.physical_address.errors }}</div>
            </div>

            <!-- POSTAL ADDRESS -->
             <div class="form-group{% if form.postal_address.errors %} has-error{% endif %}">
                <label class="control-label" for="id_postal_address">{% trans "Postal Address" %}</label>
                {% render_field form.postal_address class+="form-control input-lg" %}
                <div class="error-block">{{ form.postal_address.errors }}</div>
            </div>

             <!-- PASSWORD -->
            <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                <label class="control-label" for="id_password">{% trans "Password" %}</label>
                <div class="input-group input-group-lg">
                    {% render_field form.password class+="form-control" data-parsley-errors-container="#password-errors" %}
                    <span class="input-group-btn">
                        <button class="btn" type="button">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
                <p class="help-block small">{% trans "Your password must be alphanumeric and contain atleast one uppercase letter, number and symbol.It must also be atleast 8 digits long" %}</p>
                <div id="password-errors"></div>
                <div class="error-block">{{ form.password.errors }}</div>
            </div>

        </div>

        <!-- REDIRECT -->
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" /> {% endif %}

        <div class="text-right m-t-30">
            <button type="submit" class="btn btn-success btn-fill btn-wd btn-next">NEXT</button>
        </div>

    </form>

{% endblock page %}
{% block javascripts %}
{{ block.super }}
<script src="{% static 'js/password_widget.js' %}"></script>
{% endblock javascripts %}