config/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from apps.core.views.default import handler403, handler404, handler500, IndexPage, get_index

# from . import api

# URLs that can be seen by Swagger after one has authenticated
# public_apis = [
#     url(r'^api/v1/', include(api)),
# ]

# Remove docs from production
# schema_view = get_schema_view(
#     openapi.Info(
#         title="GAS YETU API DOCS",
#         default_version='v1',
#         description="GAS YETU APIs",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="group.rnd@jambopay.com"),
#     ),
#     permission_classes=(permissions.AllowAny,),
#     public=False,
#     patterns=public_apis,
# )

# docs = [
#     url(r'^docs/$', login_required(schema_view.with_ui('swagger',
#                                                        cache_timeout=None)), name='schema-swagger-ui'),
# ]


# urlpatterns = public_apis + docs + [
urlpatterns = [
    # url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^$', get_index, name='home'),
    url(r'^account/', include('apps.accounts.urls.default', namespace='account')),
    url(r'^account/', include('allauth.urls')),
    url(r'^distribution/', include('apps.distribution.urls.default')),
    url(r'^consumers/', include('apps.consumers.urls.default')),
    url(r'^core/', include('apps.core.urls')),
    url(r'^inventory/', include('apps.inventory.urls.default')),
    url(r'^products/', include('apps.products.urls.default')),
    url(r'^sales/', include('apps.sales.urls.default')),
    url(r'^orders/', include('apps.orders.urls.default')),
    url(r'^admin/', admin.site.urls),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^accounts/login/$', auth_views.LoginView,
        {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', auth_views.LogoutView),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_SITE_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_SITE_TITLE

apps/inventory/models.py
from django.db import models
from django.db.models import Sum

from apps.inventory.choices import DIRECTION, MOVEMENT_TYPE
from apps.products.models import Product
from apps.tenants.models import Tenant, TenantBaseModel
from apps.consumers.models import Consumer


class Reconciliation(TenantBaseModel):
    """
    Inventory reconciliation
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    reconciliation_date = models.DateTimeField()
    item_count = models.IntegerField()

    def __str__(self):
        return f'{self.product} - {self.reconciliation_date} - {self.item_count}'

    def save(self, *args, **kwargs):
        if not self.pk:
            stock_movement = StockMovement(tenant=self.tenant, product=self.product,
                                           movement_type=MOVEMENT_TYPE.Reconciliation, direction=DIRECTION.In,
                                           movement_date=self.reconciliation_date, no_of=self.item_count,
                                           transaction_entity=self.tenant)
            stock_movement.save()
            super(Reconciliation, self).save(*args, **kwargs)
        else:
            super(Reconciliation, self).save(*args, **kwargs)


class CurrentStock(TenantBaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    no_of = models.IntegerField(default=0)

    class Meta:
        unique_together = ('product', 'tenant')

    def __str__(self):
        return f'{self.tenant} - {self.product} - {self.no_of}'


class StockMovement(TenantBaseModel):
    """
    Stock Movement
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    movement_type = models.PositiveSmallIntegerField(choices=MOVEMENT_TYPE)
    direction = models.PositiveSmallIntegerField(choices=DIRECTION, default=1)
    movement_date = models.DateTimeField(auto_now_add=True, blank=True)
    no_of = models.IntegerField(help_text='Number of items moved')
    transaction_entity = models.ForeignKey(
        Tenant, on_delete=models.CASCADE, related_name="stock_movement_transaction_entity", null=True, blank=True)
    customer = models.ForeignKey(
        Consumer, on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        """
        Compute current stock with the last current stock for speed
        """
        current, _ = CurrentStock.objects.get_or_create(
            tenant=self.tenant, product=self.product)
        if self.direction == DIRECTION.In:
            current.no_of = current.no_of + self.no_of
        elif self.direction == DIRECTION.Out:
            current.no_of = current.no_of - self.no_of
        current.save()

        super(StockMovement, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.product} - {self.movement_type} - {self.no_of}'

    @property
    def stock_level(self):
        current = CurrentStock.objects.get_or_create(
            tenant=self.tenant, product=self.product)
        return current.no_of

    @property
    def complete_stock_level(self):
        """
        Property to give the current stock level, for auditing purposes
        """
        stock_in = StockMovement.objects.filter(tenant_id=self.tenant_id, product_id=self.product_id,
                                                direction=DIRECTION.In).aggregate(stock_count=Sum('no_of'))

        stock_out = StockMovement.objects.filter(tenant_id=self.tenant_id, product_id=self.product_id,
                                                 direction=DIRECTION.Out).aggregate(stock_count=Sum('no_of'))

        if not stock_in['stock_count']:
            if not stock_out['stock_count']:
                return 0
        else:
            if not stock_out['stock_count']:
                return stock_in['stock_count']

        return stock_in['stock_count'] - stock_out['stock_count']

apps/inventory/forms.py
from .models import Reconciliation
from django.forms import ModelForm


class StockReconciliationForm(ModelForm):
    class Meta:
        model = Reconciliation
        fields = (
            'product', 'item_count'
        )

apps/inventory/views/api.py
from django.db.models import Sum
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rolepermissions.mixins import HasRoleMixin

from apps.accounts.choices import EMPLOYEE
from apps.core.viewsets import ReadOnlyViewSet
from apps.distribution.models import Distributor, Retailer
from apps.inventory.models import CurrentStock, Reconciliation, StockMovement
from apps.inventory.serializers import (CurrentStockSerializer,
                                        ReconciliationSerializer,
                                        StockMovementSerializer)


class StockViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage stocks
    """
    queryset = StockMovement.objects.filter()
    serializer_class = StockMovementSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'tenant', 'product', 'movement_type', 'direction')
    allowed_roles = ['distributor_admin', 'retailer_admin']

    def get_queryset(self):
        queryset = super(StockViewSet, self).get_queryset()
        if self.request.user.profile_type == EMPLOYEE:
            employee = self.request.user.employee
            qs = StockMovement.objects.values('product').annotate(
                Sum('no_of')).filter(tenant=employee.tenant)
            return qs
        return queryset.none()


class CurrentStockViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage stocks
    """
    queryset = CurrentStock.objects.all()
    serializer_class = CurrentStockSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'tenant', 'product', 'no_of')
    allowed_roles = ['distributor_admin', 'retailer_admin']

    def get_queryset(self):
        queryset = super(CurrentStockViewSet, self).get_queryset()
        if self.request.user.profile_type == EMPLOYEE:
            employee = self.request.user.employee
            queryset = queryset.filter(tenant=employee.tenant)
            return queryset
        return queryset.none()


class ReconciliationViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage stocks
    """
    queryset = Reconciliation.objects.filter()
    serializer_class = ReconciliationSerializer
    permission_classes = (IsAuthenticated)
    filter_fields = ('id', 'tenant', 'product')
    allowed_roles = ['distributor_admin', 'retailer_admin']


class RetailerDistributorStockViewset(HasRoleMixin, ReadOnlyViewSet):
    queryset = CurrentStock.objects.all()
    serializer_class = CurrentStockSerializer
    allowed_roles = ['distributor_admin', 'retailer_admin']

    def get_queryset(self):
        queryset = super(RetailerDistributorStockViewset, self).get_queryset()

        parent_tenant = self.request.user.profile.tenant

        if 'distributors_pk' in self.kwargs:
            distributor = Distributor.objects.filter(enabled=True, pk=self.kwargs['distributors_pk'],
                                                     gas_importer=parent_tenant).first()
            if distributor:
                return queryset.filter(tenant=distributor.distributor_tenant)
            else:
                return queryset.none()
        elif 'retailers_pk' in self.kwargs:
            retailer = Retailer.objects.filter(pk=self.kwargs['retailers_pk'],
                                               enabled=True,
                                               distributor__distributor_tenant=parent_tenant).first()
            if retailer:
                return queryset.filter(tenant=retailer.retailer_tenant)
            else:
                return queryset.none()
        else:
            return queryset.none()

apps/inventory/views/default.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, View
from rolepermissions.mixins import HasRoleMixin

from apps.products.models import Product
from apps.orders.models import ProductMovement, ProductItem
from apps.tenants.models import Tenant

from ..forms import StockReconciliationForm
from ..models import CurrentStock, Reconciliation, StockMovement

from apps.orders.choices import SALE_STATUS, WITH_STATUS, PRODUCT_STATUS

from apps.distribution.models import GasImporter, Retailer
from apps.sales.models import Sale


class CurrentStockListView(HasRoleMixin, LoginRequiredMixin, ListView):
    model = CurrentStock
    template_name = 'inventory/current_stock.html'
    context_object_name = 'stocks'
    allowed_roles = ['system_admin', 'inventory_manager', 'retailer_admin']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = 'Current Stock'
        return context

    def get_queryset(self):
        tenant = self.request.user.employee.tenant
        return CurrentStock.objects.filter(tenant=tenant)


class StockMovementListView(HasRoleMixin, LoginRequiredMixin, ListView):
    model = StockMovement
    template_name = 'inventory/stock_movement.html'
    context_object_name = 'stocks'
    allowed_roles = ['system_admin', 'inventory_manager', 'retailer_admin']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = 'Stock Movement'
        return context

    def get_queryset(self):
        tenant = self.request.user.employee.tenant
        return StockMovement.objects.filter(tenant=tenant)


class StockReconciliationCreateView(HasRoleMixin, CreateView):
    model = Reconciliation
    template_name = 'inventory/reconciliation_create.html'
    form_class = StockReconciliationForm
    success_url = reverse_lazy('stock_movement')
    allowed_roles = ['system_admin', 'inventory_manager', 'retailer_admin']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = 'Reconcile stock by setting a value for current product (+ or -)'
        return context

    def form_valid(self, form):
        tenant = self.request.user.employee.tenant
        reconciliation = form.instance
        reconciliation.tenant = tenant
        reconciliation.reconciliation_date = datetime.date.today().strftime('%Y-%m-%d')
        reconciliation.save()
        return super(StockReconciliationCreateView, self).form_valid(form)


class StockProductView(HasRoleMixin, ListView):
    model = StockMovement
    template_name = 'inventory/product_view.html'
    allowed_roles = ['system_admin', 'inventory_manager', 'retailer_admin']

    def get_context_data(self, **kwargs):
        """
        product
        serial
        """
        context = super().get_context_data(**kwargs)
        tenant = self.request.tenant
        pk = self.kwargs['pk']
        product = Product.objects.filter(pk=pk).first()
        tenant = Tenant.objects.filter(title=tenant.title).first()
        if GasImporter.objects.filter(gas_importer_tenant=self.request.tenant):
            product_movements = ProductMovement.objects.filter(destination=tenant,
                                                               product_item__product=product,
                                                               product_item__sale_status=SALE_STATUS.Not_Sold,
                                                               product_item__with_status=WITH_STATUS.GasImporter,
                                                               product_item__product_status=PRODUCT_STATUS.Full,
                                                               ).all()
        if Retailer.objects.filter(retailer_tenant=self.request.tenant):
            product_movements = ProductMovement.objects.filter(destination=tenant,
                                                               product_item__product=product,
                                                               product_item__sale_status=SALE_STATUS.Sold,
                                                               product_item__with_status=WITH_STATUS.Retailer,
                                                               product_item__product_status=PRODUCT_STATUS.Full,
                                                               ).all()
        context['stocks'] = product_movements
        return context


class StockProductEmptyView(HasRoleMixin, ListView):
    model = StockMovement
    template_name = 'inventory/product_empty_view.html'
    allowed_roles = ['system_admin', 'inventory_manager', 'retailer_admin']

    def get_context_data(self, **kwargs):
        """
        product
        serial
        """
        context = super().get_context_data(**kwargs)
        tenant = self.request.tenant
        tenant = Tenant.objects.filter(title=tenant.title).first()
        if GasImporter.objects.filter(gas_importer_tenant=self.request.tenant):
            product_movements = ProductMovement.objects.filter(destination=tenant,
                                                               product_item__sale_status=SALE_STATUS.Not_Sold,
                                                               product_item__with_status=WITH_STATUS.GasImporter,
                                                               product_item__product_status=PRODUCT_STATUS.Empty,
                                                               ).all()
        if Retailer.objects.filter(retailer_tenant=self.request.tenant):
            sales = [s.get_product_item_returned for s in Sale.objects.filter(seller=tenant).all()
                     if s.get_product_item_returned.with_status == WITH_STATUS.Retailer
                     and s.get_product_item_returned.product_status == PRODUCT_STATUS.Empty
                     and s.get_product_item_returned.sale_status == SALE_STATUS.Not_Sold]
            product_movements = sales
        context['stocks'] = product_movements
        return context

apps/inventory/templates/inventory/current_stock.html
{% extends "tables.html" %} {% block page %} {% block title %} Product Listings {% endblock title %}

<p class="text-muted font-13 m-b-30">
    View current inventory here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Product</th>
            <th>Count</th>
            <th> - </th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{stock.product}}</td>
            <td>{{stock.no_of}}</td>
            <td>
                <a href="{% url 'stock_product_view' stock.product.pk %}">View Products</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page %}

apps/inventory/templates/inventory/product_empty_view.html
{% extends "tables.html" %} {% block page %} {% block title %} Empty Cylinders {% endblock title %}

<p class="text-muted font-13 m-b-30">
    View current inventory here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Product</th>
            <th>Serial No</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ forloop.counter }} {{ stock.stocks }} </td>
            {% if stock.product_item.product %}
                <td>{{stock.product_item.product}}</td>
                <td>{{stock.product_item.serial_no}}</td>
                <td>{{stock.product_item.product_status}}</td>
            {% else %}
                <td>{{stock.product}}</td>
                <td>{{stock.serial_no}}</td>
                <td>{{ stock.product_status }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page %}

apps/inventory/templates/inventory/product_view.html
{% extends "tables.html" %} {% block page %} {% block title %} Product Stock {% endblock title %}

<p class="text-muted font-13 m-b-30">
    View current inventory here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Product</th>
            <th>Serial No</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ forloop.counter }} {{ stock.stocks }} </td>
            <td>{{stock.product_item.product}}</td>
            <td>{{stock.product_item.serial_no}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page %}

apps/inventory/templates/inventory/reconciliation_create.html
{% extends "page.html" %}
{% block title %} Create Reconciliation{% endblock title %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    <form method="post" class="bootstrap3" enctype="multipart/form-data">
      {% csrf_token %} {{ form|crispy }}
      <div class="pull-right">
        <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />        
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
{% endblock page %}

apps/inventory/templates/inventory/stock_movement.html
{% extends "tables.html" %} {% block page %} {% block title %} Product Listings {% endblock title %}

<p class="text-muted font-13 m-b-30">
    View current inventory here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Product</th>
            <th>Movement Direction</th>
            <th>Movement Type</th>
            <th>No of</th>
            <th>Transaction Entity</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{stock.product}}</td>
            <td>{{stock.get_direction_display}}</td>
            <td>{{stock.get_movement_type_display}}</td>
            <td>{{stock.no_of}}</td>
            <td>{{stock.transaction_entity}}</td>
            <td>{{stock.movement_date}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page %}