config/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from apps.core.views.default import handler403, handler404, handler500, IndexPage, get_index

# from . import api

# URLs that can be seen by Swagger after one has authenticated
# public_apis = [
#     url(r'^api/v1/', include(api)),
# ]

# Remove docs from production
# schema_view = get_schema_view(
#     openapi.Info(
#         title="GAS YETU API DOCS",
#         default_version='v1',
#         description="GAS YETU APIs",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="group.rnd@jambopay.com"),
#     ),
#     permission_classes=(permissions.AllowAny,),
#     public=False,
#     patterns=public_apis,
# )

# docs = [
#     url(r'^docs/$', login_required(schema_view.with_ui('swagger',
#                                                        cache_timeout=None)), name='schema-swagger-ui'),
# ]


# urlpatterns = public_apis + docs + [
urlpatterns = [
    # url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^$', get_index, name='home'),
    url(r'^account/', include('apps.accounts.urls.default', namespace='account')),
    url(r'^account/', include('allauth.urls')),
    url(r'^distribution/', include('apps.distribution.urls.default')),
    url(r'^consumers/', include('apps.consumers.urls.default')),
    url(r'^core/', include('apps.core.urls')),
    url(r'^inventory/', include('apps.inventory.urls.default')),
    url(r'^products/', include('apps.products.urls.default')),
    url(r'^sales/', include('apps.sales.urls.default')),
    url(r'^orders/', include('apps.orders.urls.default')),
    url(r'^admin/', admin.site.urls),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^accounts/login/$', auth_views.LoginView,
        {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', auth_views.LogoutView),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_SITE_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_SITE_TITLE

apps/accounts/models.py
import logging
import time
from binascii import unhexlify

import cloudinary
import django.contrib.auth.base_user as auth_base
import django.contrib.auth.models as auth
from allauth.account.signals import password_changed, password_reset
from cloudinary.models import CloudinaryField as BaseCloudinaryField
from django.conf import settings
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django_otp.models import Device
from django_otp.oath import TOTP
from django_otp.util import hex_validator, random_hex
from simple_history.models import HistoricalRecords

from apps.accounts import messages as account_message
from apps.accounts.choices import PROFILE_TYPES
from apps.accounts.manager import UserManager
from apps.accounts.utils import default_otp_secret_key, send_sms
from apps.core.models import Location, Region, SubRegion, Village
from apps.core.utils import NullableEmailField, NullableCharField

logger = logging.getLogger(__name__)


def abstract_user_field(name):
    for f in auth.AbstractUser._meta.fields:
        if f.name == name:
            return f


class CloudinaryField(BaseCloudinaryField):
    def upload_options(self, model_instance):
        return {
            'public_id': model_instance.username,
            'unique_filename': False,
            'overwrite': True,
            'resource_type': 'image',
            'tags': ['map', 'market-map'],
            'invalidate': True,
            'quality': 'auto:eco',
        }


class User(auth_base.AbstractBaseUser, PermissionsMixin):
    username = abstract_user_field('username')
    first_name = abstract_user_field('first_name')
    last_name = abstract_user_field('last_name')
    identity_number = models.CharField(
        _('identity'), max_length=15, unique=True
    )
    image = CloudinaryField(blank=True)
    profile_type = models.PositiveSmallIntegerField(
        choices=PROFILE_TYPES, default=PROFILE_TYPES.Employee)
    email = NullableEmailField(
        _('e-mail address'), blank=True, null=True, default=None)
    phone = models.CharField(
        _('mobile number'), max_length=16, null=True,
        blank=True, default=None, unique=True
    )
    is_staff = abstract_user_field('is_staff')
    is_active = abstract_user_field('is_active')
    date_joined = abstract_user_field('date_joined')
    email_verified = models.BooleanField(default=False)
    phone_verified = models.BooleanField(default=False)
    update_profile = models.BooleanField(default=True)
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE, null=True, blank=True)
    sub_region = models.ForeignKey(
        SubRegion, on_delete=models.CASCADE, blank=True, null=True)
    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, null=True, blank=True)
    village = models.ForeignKey(
        Village, on_delete=models.CASCADE, null=True, blank=True)

    objects = UserManager()

    # Audit history
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        ordering = ('username',)
        verbose_name = _('user')
        verbose_name_plural = _('users')

    objects = UserManager()

    def __repr__(self):
        repr_string = ('<User username={obj.username}'
                       ' email={obj.email}'
                       ' email_verified={obj.email_verified}'
                       ' phone={obj.phone}'
                       ' phone_verified={obj.phone_verified}>')
        return repr_string.format(obj=self)

    @property
    def profile(self):
        """:obj:`model`: Returns the user's entity.

        Note:
            There are 3 main entities: `employee`.
        """

        if self.profile_type == 1:
            return None
        else:
            return self.employee

    def get_image_url(self):
        "Returns the avatar url."
        if self.image.url:
            return self.image.url
        return ''

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_initials(self):
        """
        Returns the initials capitalized from full name.
        """
        if self.get_full_name():
            return ''.join([x[0].upper()
                            for x in self.get_full_name().split(' ')])
        return self.username[0]

    def get_short_name(self):
        "Returns the short name for the user."
        if self.first_name:
            return self.first_name
        return self.username


@receiver(pre_delete, sender=User)
def photo_delete(sender, instance, **kwargs):
    if instance.image:
        cloudinary.uploader.destroy(instance.image.public_id)


@receiver(password_changed)
@receiver(password_reset)
def password_changed_reset(sender, request, user, **kwargs):
    if user.phone:
        send_sms(user.phone, account_message.password_change_or_reset)


class OTPVerificationDevice(Device):
    unverified_phone = models.CharField(max_length=16)
    secret_key = models.CharField(
        max_length=40,
        default=default_otp_secret_key,
        validators=[hex_validator],
        help_text="Hex-encoded secret key to generate totp tokens.",
        unique=True,
    )
    last_verified_counter = models.BigIntegerField(
        default=-1,
        help_text=("The counter value of the latest verified token."
                   "The next token must be at a higher counter value."
                   "It makes sure a token is used only once.")
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    label = models.CharField(max_length=20,
                             choices=(('phone_verify', _("Verify Phone")),
                                      ('password_reset', _("Reset Password"))),
                             default='phone_verify')
    verified = models.BooleanField(default=False)

    step = settings.TOTP_TOKEN_VALIDITY
    digits = settings.TOTP_DIGITS

    class Meta(Device.Meta):
        verbose_name = "OTP Verification Devices"

    @property
    def bin_key(self):
        return unhexlify(self.secret_key.encode())

    def totp_obj(self):
        totp = TOTP(key=self.bin_key, step=self.step, digits=self.digits)
        totp.time = time.time()
        return totp

    def generate_challenge(self):
        totp = self.totp_obj()
        token = str(totp.token()).zfill(self.digits)

        message = _("Your One Time Password for Gas Yetu is {token_value}."
                    " It is valid for {time_validity} minutes.")
        message = message.format(
            token_value=token, time_validity=self.step // 60)

        send_sms(phone_number=self.unverified_phone, sms_body=message)
        return token

    def verify_token(self, token, tolerance=0):
        totp = self.totp_obj()
        if ((totp.t() > self.last_verified_counter) and
                (totp.verify(token, tolerance=tolerance))):
            self.last_verified_counter = totp.t()
            self.verified = True
            self.save()
        else:
            self.verified = False
        return self.verified


class Invitations(models.Model):
    email = models.EmailField(max_length=70)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = _('invitations')
        verbose_name_plural = _('invitations')

apps/accounts/templates/accounts/invalid.html
{% extends "account/snippets/base.html" %}
{% load sass_tags %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% block title %} Sign In {% endblock title %}

{% block content %}

<div class="row">

    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
        <h1 style="color:white; text-align:center;">{{message}}</h1>
        <br>
        <a href="/" style="background-color: #7A9E9F; color:white" class="btn btn-primary btn-lg btn-block btn-link text-uppercase"
            role="button">
            {% trans 'Go back home' %}
        </a>
    </div>
</div>
{% endblock content %}

apps/accounts/templates/accounts/invite_user.html
{% extends "tables.html" %}
{% load sass_tags %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %} Invite User {% endblock title %}

{% block page %}

{% include 'messages.html' %}
    <form action="{% url 'account:invite_user' %}" method="post">
        {% csrf_token %}
        <div class="form-group {% if form.email.errors %} has-error {% endif %}">
            <label class="control-label" for="{{ form.email.id_for_label }}">{% trans "Email Address" %}</label>
            {% render_field form.email class+="form-control input-lg" data-parsley-required="true" data-parsley-sanitize="1"%}
            <div class="error-block">
                {{ form.email.errors }}
            </div>
        </div>
        <div class="form-group {% if form.roles.errors %} has-error {% endif %}">
            <label class="control-label" for="{{ form.roles.id_for_label }}">{% trans "Role" %}</label>
            {% render_field form.roles class+="form-control input-lg" data-parsley-required="true" data-parsley-sanitize="1"%}
            <div class="error-block">
                {{ form.roles.errors }}
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-fill btn-danger btn-wd">{% trans "Send Invite" %}</button>
        </div>
    </form>
{% endblock page %}

apps/accounts/templates/accounts/manage_roles.html
{% extends "tables.html" %}
{% load sass_tags %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %} Manage Roles {% endblock title %}

{% block page %}

{% include 'messages.html' %}
{% block header_javascripts %}
    <link href="{% static 'css/manage-users.css' %}" rel="stylesheet" />
{% endblock header_javascripts %}
<div class="row">
    <div class="col-md-2">
        <h4>Users</h4>
        <ul id="users_ul" class="nav nav-pills nav-stacked">
            {% for role in user_roles %}
            <li data-user-id="{{role.user.id}}" class="username">
                <span>{{role.user.get_full_name}}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div data-roles-url="{% url 'account:ajax_load_roles_data' %}" data-remove-roles-url="{% url 'account:ajax_remove_user_role' %}" data-remove-all-roles-url="{% url 'account:ajax_remove_all_user_role'%}" id="roles" class="col-md-10">
        <h4>Roles</h4>
        <ul class="list-group" id='id_roles' >

        </ul>
        <span>
            <div class="row">
                    <div class="form-group col-md-6">
                            <select class="form-control input-lg add-role" data-add-roles-url='{% url "account:ajax_add_user_role" %}' >
                                    <option value="">Add New Role</option>

                                    {% for role in all_roles %}
                                        <option value="{{role.0}}">{{role.1}}</option>
                                    {% endfor %}

                                </select>
                    </div>
                    <div class="form-group col-md-6">
                        <button class="btn btn-danger btn-fill" id='remove-all'>Remove all Roles</button>

                    </div>
            </div>


        </span>
    </div>
</div>
{% endblock page %}

{% block extended_js %}
<script>
        function notify_long(message, type) {
            var notify_type = type.toLowerCase()
            if (notify_type == 'error') {
                notify_type = 'danger'
            }
            $.notify({
                message: message,
            }, {
                placement: {
                    from: "top",
                    align: "right"
                },
                type: notify_type
            });

        }
    $("#users_ul").on("click", ".username", function (event) {
        var userId = $(this).closest('li').attr('data-user-id');
        $('ul li.active').removeClass('active');
        $(this).closest('li').addClass('active');
        getRoles(userId);
    });

    $('#roles').on('change', '.add-role', function(e){
        var userId = $('#id_roles').attr('data-user-id');
        var role = $(this).val()

        if(!role || !userId){
            return
        }

        $.ajax({
            url: $(this).attr("data-add-roles-url"),
            data: {
                'user_id': userId,
                'role':role,
            },
            success: function (data) {
                render_roles(data)
                notify_long("Successfully Added Role", 'Success')
                $('.add-role')[0].selectedIndex = 0;


            }
        });

    })

    $('#roles').on('click','.remove-role-wrapper', function(e){

        var role = $(this).closest('li').attr('data-role-value')
        var userId = $('#id_roles').attr('data-user-id');

        $.ajax({
            url: $('#roles').attr("data-remove-roles-url"),
            data: {
                'user_id': userId,
                'role':role,
            },
            success: function (data) {
                render_roles(data)
                notify_long("Successfully Removed Role", 'Success')

            }
        });



    } )

    $('#remove-all').click(function(e){

        var userId = $('#id_roles').attr('data-user-id');

        $.ajax({
            url: $('#roles').attr("data-remove-all-roles-url"),
            data: {
                'user_id': userId,
            },
            success: function (data) {
                render_roles(data)
                notify_long("Successfully Removed All Roles", 'Success')

            }
        });



    } )



    function getRoles(userId) {
        $('#id_roles').attr('data-user-id', userId);
        $.ajax({
            url: $("#roles").attr("data-roles-url"),
            data: {
                'user_id': userId,
            },
            success: function (data) {
                render_roles(data)

            }
        });
    }

    function render_roles(data){
        $('#id_roles').empty();
        var items = [];
        $.each(data['roles'], function (i, item) {
            items.push('<li class="list-group-item" data-role-value='+item.value+'>' + item.name + ' <span class="remove-role-wrapper"><i class="fa fa-times-circle text-danger remove-role" title="Remove Role"></i></span></li>');
        });
        $('#id_roles').append(items.join(''));
    }

    $(document).ready(function(){
        $('.username').first().click()
    })


</script>
{% endblock %}

apps/accounts/templates/accounts/register_basic.html
{% extends "account/signup.html" %} {% load sass_tags %} {% load widget_tweaks %} {% load static %} {% load i18n %} 
{% block inner_content %}
<form class="account-register-basic form-narrow form-2col" id="signup_form" method="POST" action="" data-parsley-validate data-parsley-excluded=":hidden">
    {% csrf_token %} {{ wizard.management_form }}
    <div class="row">
        <span style="font-size: 35px;">Create New Account</span>
        <p><b>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</b></p>
        <hr>
    </div>
    <div class="row">
        <!-- FIRST NAME -->
        <div class="form-group{% if form.first_name.errors %} has-error{% endif %}">
            <label class="control-label" for="id_first_name">{% trans "First Name" %}</label>
            {% render_field form.first_name class+="form-control input-lg" %}
            <div class="error-block">{{ form.first_name.errors }}</div>
        </div>

        <!-- LAST NAME -->
        <div class="form-group{% if form.last_name.errors %} has-error{% endif %}">
            <label class="control-label" for="id_last_name">{% trans "Last Name" %}</label>
            {% render_field form.last_name class+="form-control input-lg" %}
            <div class="error-block">{{ form.last_name.errors }}</div>
        </div>

        <!-- PHONE -->
        <div class="form-group{% if form.phone.errors %} has-error{% endif %}">
            <label class="control-label" for="id_phone">{% trans "Phone" %}</label>
            {% render_field form.phone class+="form-control input-lg" placeholder="07xxxxxxx" data-parsley-required="true" data-parsley-errors-container="#phone-errors" %}
            <p class="help-block small">{% trans "Phone numbers must start with 07 and contain 10 digits" %}</p>
            <div id="phone-errors"></div>
            <div class="error-block">{{form.phone.errors}}</div>
        </div>

        <!-- EMAIL -->
        <div class="form-group{% if form.email.errors %} has-error{% endif %}">
            <label class="control-label" for="id_email">{% trans "Email" %}</label>
            {% render_field form.email class+="form-control input-lg" data-parsley-required="true" %}
            <div class="error-block">{{ form.email.errors }}</div>
            <div>
            </div>
        </div>

        <!-- PASSWORD -->
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
            <label class="control-label" for="id_password">{% trans "Password" %}</label>
            <div class="input-group input-group-lg">
                {% render_field form.password class+="form-control" data-parsley-minlength="4" data-parsley-character="3" data-parsley-userfield="1" data-parsley-emailfield="1" data-parsley-phonefield="1" data-parsley-errors-container="#password-errors" %}
                <span class="input-group-btn">
                    <button class="btn" type="button">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
            <p class="help-block small">{% trans "Your password must be numeric and 4 digits long" %}</p>
            <div id="password-errors"></div>
            <div class="error-block">{{ form.password.errors }}</div>
        </div>
    </div>

    <!-- REDIRECT -->
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" /> {% endif %}

    <!-- BUTTONS
                <button type="submit" name="register" class="btn btn-primary btn-lg btn-block text-uppercase">
                    {% trans "Register" %}
                </button> -->

    <!-- BUTTONS -->
    <div class="text-right m-t-30">
        <button type="submit" class="btn btn-success btn-fill btn-wd btn-next">NEXT</button>
    </div>

</form>
{% endblock inner_content %}

apps/accounts/templates/accounts/register_final.html
{% extends "account/signup.html" %} {% load sass_tags %} {% load widget_tweaks %} {% load static %} {% load i18n %}
{% block inner_content %}
<form class="account-register-basic form-narrow form-2col" id="signup_form" method="POST" action="" data-parsley-validate data-parsley-excluded=":hidden">
    {% csrf_token %} {{ wizard.management_form }}
    <div class="row">
        <span style="font-size: 35px;">Create New Account</span>
        <p><b>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</b></p>
        <hr>
    </div>
    <div class="row">
        <!-- IDENTITY NUMBER -->
        <div class="form-group{% if form.identity_number.errors %} has-error{% endif %}">
            <label class="control-label" for="id_identity_number">{% trans "Identity Number" %}</label>
            {% render_field form.identity_number class+="form-control input-lg" data-parsley-minlength="7" data-parsley-maxlength='10'%}
            <div class="error-block">{{ form.identity_number.errors }}</div>
        </div>

        <!-- REGION -->
        <div class="form-group{% if form.region.errors %} has-error{% endif %}">
            <label class="control-label" for="id_region">{% trans "County" %}</label>
            {% render_field form.region class+="form-control input-lg" %}
            <div class="error-block">{{ form.region.errors }}</div>
        </div>

        <!-- SUB REGION -->
        <div class="form-group{% if form.sub_region.errors %} has-error{% endif %}">
            <label class="control-label" for="id_sub_region">{% trans "Sub County" %}</label>
            {% render_field form.sub_region class+="form-control input-lg" %}
            <div class="error-block">{{ form.sub_region.errors }}</div>
        </div>

        <!-- LOCATION -->
        <div class="form-group{% if form.location.errors %} has-error{% endif %}">
            <label class="control-label" for="id_location">{% trans "Location" %}</label>
            {% render_field form.location class+="form-control input-lg" %}
            <div class="error-block">{{ form.location.errors }}</div>
        </div>

        <!-- VILLAGE -->
        <div class="form-group{% if form.village.errors %} has-error{% endif %}">
            <label class="control-label" for="id_village">{% trans "Village" %}</label>
            {% render_field form.village class+="form-control input-lg" %}
            <div class="error-block">{{ form.village.errors }}</div>
        </div>

        <!-- SURVEY -->
        <div class="form-group{% if form.survey_requested.errors %} has-error{% endif %}">
            <label class="control-label" for="id_survey_requested">{% trans "Do you wish to enroll to gasyetu subsidized gas?" %}</label>
            {% render_field form.survey_requested class+="form-control input-lg" %}
            <div class="error-block">{{ form.survey_requested.errors }}</div>
        </div>
    </div>

    <!-- REDIRECT -->
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" /> {% endif %}

    <div class="text-right m-t-30">
        {% if wizard.steps.prev %}
            <button name="wizard_goto_step" formnovalidate type="submit" value="{{ wizard.steps.prev }}" class="btn btn-default btn-fill btn-wd btn-next btn-reset">{% trans "PREVIOUS" %}</button>
        {% endif %}
        <button type="submit" class="btn btn-success btn-fill btn-wd btn-next">FINISH</button>
    </div>

</form>
{% endblock inner_content %}

{% block extended_js %}
{{ form.media.js }}
{% endblock extended_js %}

apps/accounts/templates/accounts/staff_register.html
{% extends "account/snippets/base.html" %}
{% load sass_tags %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% block title %} Staff Register {% endblock title %}

{% block content %}


<form method="post" class="login-form form-narrow" enctype="multipart/form-data" data-parsley-validate data-parsley-excluded=":hidden">
	{% csrf_token %}
	<div class="row">
		<span style="font-size: 25px;">Complete Registration</span>
		<hr>
	</div>
	<div class="card card-plain">
		<div class="content">
			<!-- EMAIL -->
			<div id="email-div" class="clearfix form-group{% if form.email.errors %} has-error{% endif %}">
					<div class="input-group">
						{% render_field form.email class+="form-control input-lg" placeholder="Email Address" data-parsley-sanitize="1" data-parsley-required="true" %}
						<span class="input-group-addon">
								<i style="color:green" class="fa fa-check"></i>
						</span>
					</div>
					<div class="error-block">{{ form.email.errors }}</div>
			</div>
			
			<!-- FIRST NAME -->
			<div class="form-group{% if form.first_name.errors %} has-error{% endif %}">
				{% render_field form.first_name class+="form-control input-lg" placeholder="Your First Name" data-parsley-minlength="3" data-parsley-sanitize="1" %}
				<div class="error-block">{{ form.first_name.errors }}</div>
			</div>

			<!-- LAST NAME -->
			<div class="form-group{% if form.last_name.errors %} has-error{% endif %}">
				{% render_field form.last_name class+="form-control input-lg" placeholder="Your Last Name" data-parsley-minlength="3" data-parsley-sanitize="1" %}
				<div class="error-block">{{ form.last_name.errors }}</div>
			</div>
			
			<!-- PASSWORD -->
			<div class="form-group{% if form.password.errors %} has-error{% endif %}">
				{% render_field form.password class+="form-control" placeholder="Password" data-parsley-errors-container="#password-errors" %}
				<p class="help-block small">{% trans "Enter a strong password" %}</p>
				<div class="error-block">{{ form.password.errors }}</div>
			</div>
		</div>
		<div class="footer text-center">
			<button type="submit" class="btn btn-fill btn-danger btn-wd">Create Account</button>
		</div>
	</div>
</form>
						
{% endblock content %}

apps/accounts/templates/accounts/topup.html
{% extends "tables.html" %}
{% load sass_tags %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %} Top Up Wallet via M-PESA {% endblock title %}

{% block page %}

{% include 'messages.html' %}
    <form action="{% url 'account:account_topup' %}" method="post">
        {% csrf_token %}
        <div class="form-group {% if form.phone.errors %} has-error {% endif %}">
            <label class="control-label" for="{{ form.phone.id_for_label }}">{% trans "Phone Number" %}</label>
            {% render_field form.phone class+="form-control input-lg" data-parsley-required="true" data-parsley-sanitize="1"%}
            <div class="error-block">
                {{ form.phone.errors }}
            </div>
        </div>
        <div class="form-group {% if form.amount.errors %} has-error {% endif %}">
            <label class="control-label" for="{{ form.amount.id_for_label }}">{% trans "Amount" %}</label>
            {% render_field form.amount class+="form-control input-lg" data-parsley-required="true" data-parsley-sanitize="1"%}
            <div class="error-block">
                {{ form.amount.errors }}
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-fill btn-danger btn-wd">{% trans "Top Up" %}</button>
        </div>
    </form>
{% endblock page %}