config/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from apps.core.views.default import handler403, handler404, handler500, IndexPage, get_index

# from . import api

# URLs that can be seen by Swagger after one has authenticated
# public_apis = [
#     url(r'^api/v1/', include(api)),
# ]

# Remove docs from production
# schema_view = get_schema_view(
#     openapi.Info(
#         title="GAS YETU API DOCS",
#         default_version='v1',
#         description="GAS YETU APIs",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="group.rnd@jambopay.com"),
#     ),
#     permission_classes=(permissions.AllowAny,),
#     public=False,
#     patterns=public_apis,
# )

# docs = [
#     url(r'^docs/$', login_required(schema_view.with_ui('swagger',
#                                                        cache_timeout=None)), name='schema-swagger-ui'),
# ]


# urlpatterns = public_apis + docs + [
urlpatterns = [
    # url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^$', get_index, name='home'),
    url(r'^account/', include('apps.accounts.urls.default', namespace='account')),
    url(r'^account/', include('allauth.urls')),
    url(r'^distribution/', include('apps.distribution.urls.default')),
    url(r'^consumers/', include('apps.consumers.urls.default')),
    url(r'^core/', include('apps.core.urls')),
    url(r'^inventory/', include('apps.inventory.urls.default')),
    url(r'^products/', include('apps.products.urls.default')),
    url(r'^sales/', include('apps.sales.urls.default')),
    url(r'^orders/', include('apps.orders.urls.default')),
    url(r'^admin/', admin.site.urls),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^accounts/login/$', auth_views.LoginView,
        {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', auth_views.LogoutView),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_SITE_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_SITE_TITLE

apps/products/models.py
from django.db import models

from apps.products.choices import BILLING_MODE, SERVICE_CHOICES
from apps.tenants.models import TenantBaseModel, Tenant, BaseModel


class Cylinder(BaseModel):
    """
    List of Cylinder Sizes. E.g. 13 KG, 6Kg
    """
    title = models.CharField(max_length=100, unique=True)

    class Meta:
        unique_together = ('title',)

    def __str__(self):
        return self.title


class Brand(BaseModel):
    """
    List of Brands
    """
    title = models.CharField(max_length=100, unique=True)
    tenant = models.ForeignKey(
        Tenant, on_delete=models.CASCADE, related_name='brand_tenant', null=True, blank=True)

    class Meta:
        unique_together = (('title'),)

    def save(self, *args, **kwargs):
        self.title = self.title.upper()
        self.tenant = self.tenant
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Product(BaseModel):
    """
    Product/Gas offered in the system. E.g. Gas-13KG, Gas-6KG
    """
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    cylinder = models.ForeignKey(Cylinder, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('brand', 'cylinder',)

    @property
    def title(self):
        return f'{self.brand}-{self.cylinder}'

    def __str__(self):
        return self.title


class Listing(TenantBaseModel):
    """
    Listings offered by a company/tenant
    """
    service = models.CharField(choices=SERVICE_CHOICES, max_length=32)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    list_price = models.DecimalField(
        max_digits=10, decimal_places=2, help_text='List Price')
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = (('tenant', 'service', 'product'),)

    def __str__(self):
        return '{} - {} - {} - {}'.format(self.tenant.title, self.service, self.product, self.list_price)


class Discount(TenantBaseModel):
    """
    Details of discounts offered
    """
    merchant = models.ForeignKey(
        Tenant, on_delete=models.CASCADE, related_name='merchant_discount_rule')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    billing_mode = models.PositiveSmallIntegerField(choices=BILLING_MODE)
    item_count = models.PositiveSmallIntegerField(null=True, blank=True,
                                                  help_text='value to be checked so as to qualify for the discount '
                                                            'E.g. 1 cylinder')
    discount_rate = models.DecimalField(max_digits=10, decimal_places=3,
                                        help_text='Percentage Value or Fixed amount value')
    discount_type = models.PositiveSmallIntegerField()
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = (('tenant', 'title'),
                           ('merchant', 'discount_type', 'billing_mode', 'item_count'))

    def __str__(self):
        return '{} ({} - {})'.format(self.title, self.discount_type, self.billing_mode)

apps/products/forms.py
from django import forms
from django.conf import settings
from django.forms import BaseFormSet, ModelForm, SelectDateWidget
from django.forms.widgets import Select

from .models import Brand, Cylinder, Listing, Product


class CylinderForm(ModelForm):
    class Meta:
        model = Cylinder
        fields = (
            'title',
        )


class BrandForm(ModelForm):
    class Meta:
        model = Brand
        fields = (
            'title',
        )


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = (
            'brand', 'cylinder'
        )

    def __init__(self, *args, **kwargs):
        disabled = kwargs.pop('disabled', None)
        super().__init__(*args, **kwargs)
        if disabled:
            self.fields['cylinder'].widget.attrs['disabled'] = True
            self.fields['brand'].widget.attrs['disabled'] = True


class ProductListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = (
            'service', 'product', 'list_price'
        )

    def __init__(self, *args, **kwargs):
        super(ProductListingForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['service'].disabled = True
            self.fields['product'].disabled = True


class SerialForm(forms.Form):
    serial_number = forms.CharField(
        max_length=32, label="Enter Serial Number", required=False)


class BaseSerialsFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseSerialsFormSet, self).__init__(*args, **kwargs)


class UploadSerialsForm(forms.Form):
    serial_file = forms.FileField(label="Upload Excel File", required=True)

apps/products/views/api.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rolepermissions.mixins import HasRoleMixin

from apps.accounts.choices import BENEFICIARY, CONSUMER, EMPLOYEE
from apps.distribution.models import Distributor, Retailer
from apps.products.models import Brand, Cylinder, Discount, Listing, Product
from apps.products.serializers import (BrandSerializer, CylinderSerializer,
                                       DiscountSerializer, ListingSerializer,
                                       ProductSerializer)
from apps.tenants.choices import DISTRIBUTOR, RETAILER


class ProductViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage Products
    """
    queryset = Product.objects.filter()
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'cylinder', 'brand')
    allowed_roles = ['distributor_admin',
                     'retailer_admin', 'beneficiary', 'consumer']


class ListingViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage Listings
    """
    queryset = Listing.objects.all()
    serializer_class = ListingSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'tenant')
    allowed_roles = ['distributor_admin',
                     'retailer_admin', 'beneficiary', 'consumer']

    def get_queryset(self):

        queryset = super(ListingViewSet, self).get_queryset()

        if self.request.user.profile_type == EMPLOYEE:
            employee = self.request.user.employee

            if employee.tenant.tenant_type == RETAILER:
                tenant = Retailer.objects.get(
                    retailer_tenant=employee.tenant).distributor.distributor_tenant
                queryset = queryset.filter(tenant=tenant)
                return queryset

            elif employee.tenant.tenant_type == DISTRIBUTOR:
                tenant = Distributor.objects.get(
                    distributor_tenant=employee.tenant).gas_importer.gas_importer_tenant
                queryset = queryset.filter(tenant=tenant)
                return queryset

        elif self.request.user.profile_type == CONSUMER:
            queryset = queryset.filter(
                for_consumer=True, product__gas_yetu=False)

        elif self.request.user.profile_type == BENEFICIARY:
            queryset = queryset.filter(
                for_consumer=True)

            if self.request.user.profile.has_benefited:
                queryset = queryset.exclude(product__gas_yetu=True)

        else:
            return queryset.none()

        agent_number = self.request.query_params.get('agent_number')

        if agent_number:
            distributor = Distributor.objects.filter(enabled=True,
                                                     agent_number=agent_number).first()

            if distributor:
                return queryset.filter(tenant=distributor.distributor_tenant)
            else:
                retailer = Retailer.objects.filter(
                    enabled=True,
                    agent_number=agent_number).first()
                if retailer:
                    return queryset.filter(tenant=retailer.retailer_tenant)
        else:
            return queryset

        return queryset.none()


class BrandViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage Brands
    """
    queryset = Brand.objects.filter()
    serializer_class = BrandSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'title')
    allowed_roles = ['distributor_admin',
                     'retailer_admin', 'beneficiary', 'consumer']


class CylindersViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage stocks
    """
    queryset = Cylinder.objects.filter()
    serializer_class = CylinderSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'title')
    allowed_roles = ['distributor_admin',
                     'retailer_admin', 'beneficiary', 'consumer']


class DiscountViewSet(HasRoleMixin, viewsets.ModelViewSet):
    """
    Manage Discount
    """
    queryset = Discount.objects.filter()
    serializer_class = DiscountSerializer
    permission_classes = (IsAuthenticated,)
    filter_fields = ('id', 'tenant', 'merchant', 'product', 'service', 'title',
                     'billing_mode', 'item_count', 'discount_rate',
                     'discount_type', 'start_date', 'end_date')
    allowed_roles = ['distributor_admin',
                     'retailer_admin', 'beneficiary', 'consumer']

apps/products/templates/products/product_serials/product_serial_edit.html
{% extends "page.html" %}
{% load static %}
{% load permission_tags %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %} Edit Product Serial{% endblock title %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock stylesheets %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    <form action="" id="productForm" data-listings-url="{% url 'ajax_load_listings' %}" novalidate method="post">
        {% csrf_token %}       
        <fieldset>
            <div class="form-group {% if product_form.brand.errors %} has-error {% endif %}" disabled>
                <label class="control-label" for="{{ form.token.id_for_label }}">{% trans "Product" %}</label>
                <div class="input-group">
                    {% render_field product_form.brand class+="form-control input-md" data-parsley-required="true" data-parsley-sanitize="1"%}
                </div>
                <div class="error-block">
                    {{ product_form.brand.errors }}
                </div>
            </div>
            {{ product_form|crispy }}
        </fieldset>

        {{ product_serial_formset.management_form|crispy }}

        <fieldset>        
        <table class="table">
                {% for form in product_serial_formset %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                        
                    </tr>
                {% endfor %}
        </table>
        </fieldset>

        <div class="pull-right">
            <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />        
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock page %}
{% block javascripts %}
{{ block.super }}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'Add product serial',
        deleteText: 'Remove',
        //prefix: 'productserial_set'
        prefix: '{{ product_serial_formset.prefix }}'
    });

    $(".delete-row").on('click', function(){
        let count = parseInt($('#id_productitem_set-TOTAL_FORMS').val());
        $('#id_order_items-TOTAL_FORMS').val(count-1);
    });


    let btn = $(".add-row");
    btn.data("funcToCall", btn.attr("onclick"));
    $(".add-row").removeAttr("onclick");
    $(".add-row").bind("click", function(e){
        let func = $(this).data("funcToCall");
        eval(func);
        let count = parseInt($('#id_productitem_set-TOTAL_FORMS').val());
        $('#id_productitem_set-TOTAL_FORMS').val(count+1);
    });
</script>
{% endblock javascripts %}

apps/products/templates/products/product_serials/product_serial_upload.html
{% extends "page.html" %}
{% load static %}
{% load permission_tags %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %} Upload Product Serials{% endblock title %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock stylesheets %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    <form action="" id="id_serial_upload_Form" enctype="multipart/form-data" data-listings-url="{% url 'import_serial' %}" novalidate method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="customer_name">Brand</label>
            <input type="text" class="form-control" name="brand" value="{{ brand }}" required>
        </div>
        <div class="form-group">
            <label for="cylinder_size">Cylinder Size</label>
            <select class="form-control" name="cylinder_size" id="id_cylinder_size" onload="get_cylinder_size();" required>
                <option value="">Please Select Cylinder</option>
            </select>
        </div>
        <div>
            <label for="serial_file">Upload Excel File</label>
            <input type="file" name="serial_file" id="id_serial_file" required>
        </div>

        <div class="pull-right">
            <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>
    </form>
{% endblock page %}
{% block javascripts %}
{{ block.super }}
    <script type="application/javascript">
        function get_cylinder_size() {
            $("#id_cylinder_size").empty();
            $.ajax({
                type: 'GET',
                url: '/products/get_cylinder_size/',
                success: function (data) {
                    let parsed = $.parseJSON(data);
                    parsed.forEach(function (record) {
                        $("#id_cylinder_size").prepend("<option value='" + record.id + "'>" + record.title + "</option>");
                    });
                },
                error: function (data) {
                    $("#id_cylinder_size").prepend("<option value='' selected='selected'>--------------</option>");
                },
            });
        }
        get_cylinder_size();
    </script>
{% endblock javascripts %}

apps/products/templates/products/product_serials/product_serials_list.html
{% extends "tables.html" %} {% block page %} {% block title %} Products {% endblock title %}

<p class="text-muted font-13 m-b-30">
    Manage products serials here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Brand</th>
            <th>Cylinder</th>
            <th class="dt-center"></th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ forloop.counter }} {{ product.products }} </td>
            <td>{{product.brand}}</td>
            <td>{{product.cylinder}}</td>
            <td class="last">
                <a style='color:green' href="{% url 'product-serials_edit' product.id %}">View Serials</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page %} {% block extended_js %}
<script>
    $('#datatable-responsive').dataTable({
        columnDefs: [
            { targets: [2, 3], "orderable": false },
        ]
    });
</script> {% endblock extended_js %}